apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql
        labels:
              app: mysql
spec:
        selector:
                matchLabels:
                        app: mysql
        template:
                metadata:
                        labels:
                                app: mysql
                spec:
                        containers:
                                - name: mysql
                                  image: mysql:5.7
                                  env:
                                          - name: MYSQL_ROOT_PASSWOR
                                            value: password
                                          - name: MYSQL_DATABASE
                                            value: springtodo
