apiVersion: v1
kind: ConfigMap
metadata:
        name: nginx-config
data:
     default.conf: |
             server {
                     listen:80;
                     location / {
                                proxy_pass http://todofront:3000;
                     }
                     location /api/ {
                                proxy_pass http://springtodo:8585;
                     }
             }
