apiVersion: v1
kind: Service
metadata:
        name: todofront
spec:
    selector:
            app: todofront
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: ClusterIP
