apiVersion: apps/v1
kind: Deployment
metadata:
        name: springtodo
        labels:
              app: springtdo
spec:
    selector:
            matchLabels:
                       app: springtodo
    template:
            metadata:
                    labels:
                          app: springtodo
            spec:
                containers:
                        - name: springtdo
                          image: michealbmullin/todoback
                          env:
                            - name: MYSQL_IP
                              value: mysql
                          ports:
                             - containerPort: 8585
