apiVersion: v1
kind: Service
metadata:
        name: springtodo
spec:
    selector:
            app: springtodo
    ports:
       - protocol: TCP
         port: 8585
         targetPort: 8585
    type: ClusterIP
